apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-web-app
  template:
    metadata:
      labels:
        app: devops-web-app
    spec:
      containers:
        - name: devops-web-app
          image: shabbirislam/devops-web-app:11
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
